version: '3.8'


services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: alberto
      POSTGRES_PASSWORD: oing1234
      POSTGRES_DB: mastermindb
    ports:
      - "5434:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data


volumes:
  postgres-data:
